import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import ThemeProviderC from "./_components/util/ThemeProvider";
import { ThemeSwitcher } from "./_components/UI/ThemeSwitcher";
import { Navigation } from "./_components/Navigation/Navigation";
import { RQProvider } from "./_components/util/RQProvider";

const roboto = Roboto({
  weight: ["400", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${poppins.variable}`}>
        <RQProvider>
          <ThemeProviderC>
            <ThemeSwitcher />
            <Navigation />
            {children}
          </ThemeProviderC>
        </RQProvider>
      </body>
    </html>
  );
}
