import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import { ThemeProviderC } from "./_components/utils/ThemeProviderC";
import { RQProvider } from "./_components/utils/RQProvider";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} font-sans bg-base-100 text-base-content dark:text-base-100 dark:bg-base-content`}
      >
        <RQProvider>
          <ThemeProviderC>{children}</ThemeProviderC>
        </RQProvider>
      </body>
    </html>
  );
}
