import "./globals.css";
import type { Metadata } from "next";
import localFont from "@next/font/local";
import { Inconsolata } from "next/font/google";
import { RQProvider } from "./_components/utils/RQProvider";
import { Navigation } from "./_components/Navigation/Navigation";
const inconsolata_f = Inconsolata({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-inconsolata",
});
const labGrotesque = localFont({
  src: [
    {
      path: "./../public/fonts/LabGrotesque-Thin.ttf",
      weight: "100",
    },
    {
      path: "./../public/fonts/LabGrotesque-Light.ttf",
      weight: "300",
    },
    {
      path: "./../public/fonts/LabGrotesque-Regular.ttf",
      weight: "400",
    },
    {
      path: "./../public/fonts/LabGrotesque-Medium.ttf",
      weight: "500",
    },
    {
      path: "./../public/fonts/LabGrotesque-Bold.ttf",
      weight: "700",
    },
    {
      path: "./../public/fonts/LabGrotesque-Black.ttf",
      weight: "900",
    },
  ],
  variable: "--font-lab-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${labGrotesque.variable} ${inconsolata_f.variable} bg-base-100 text-base-content font-labGrotesque text-body-mobile md:text-body `}
      >
        <RQProvider>
          <Navigation />
          {children}
        </RQProvider>
      </body>
    </html>
  );
}
